sql_to_django/urls.py
from django.urls import path

from sql_to_django import views
from .views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

sql_to_orm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('sql_to_django.urls')),
    path('admin/', admin.site.urls),
]

common/models.py
from django.db import models

# Create your models here.

sql_to_django/models.py
from django.db import models

# Create your models here.

sql_to_django/forms.py
from django import forms

from sql_to_django.widgets import DivContentEditable


class QueryInputForm(forms.Form):
    query = forms.CharField(max_length=1000, widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Please input working SQL query.'}))

common/views.py
from django.shortcuts import render

sql_to_django/views.py
from django.shortcuts import render, redirect
from django.views.generic import FormView
from django.contrib import messages

from common.lib import list_to_dict, list_whitespace_remove
from sql_to_django.forms import QueryInputForm
from sql_to_django.lib import QueryFuncManager
import re


class IndexView(FormView):
    template_name = 'index.html'

    def get_form(self, form_class=None):
        return QueryInputForm(self.request.POST)

    def form_valid(self, form):
        context = self.get_context_data()
        try:
            query = re.split(r'(select|\w+\souter\sjoin|\w+\sjoin|where|\w+\sby)', form.data['query'])
            query = list_whitespace_remove(query)
            query_dict = list_to_dict(query)
            print(query_dict)
            orm = []
            for key in query_dict:
                orm.append(QueryFuncManager.get_query(f'{key}', query=query_dict[key]).get_orm())
            context['orm'] = ''.join(orm)
            print(orm)
        except:
            messages.error(self.request, '올바르지 않은 문법입니다.')
        return render(self.request, self.template_name, context)

    def form_invalid(self, form):
        print(form.errors)
        return super(IndexView, self).form_invalid(form)

common/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="utf-8">
    <title>SQL To Django ORM</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/a9fabb7577.js" crossorigin="anonymous"></script>
	<link href="{% static "css/custom.css" %}" rel="stylesheet" type="text/css">
    {% block header-css %}
    {% endblock header-css %}
</head>
<body>
<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">About</h4>
                    <p class="text-muted">Convert SQL to Django ORM :)</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Contact</h4>
                    <ul class="list-unstyled">
                        <li><a href="#" class="text-white"><i class="fab fa-github"></i> GitHub</a></li>
                        <li><a href="https://velog.io/@rimi" class="text-white"><i class="fas fa-blog"></i> Blog</a>
                        </li>
                        <li><a href="mailto:yerimi@kakao.com" class="text-white"><i class="fas fa-envelope"></i> Email
                            me</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
            <a href="{% url "index" %}" class="navbar-brand d-flex align-items-center">
                <i class="fas fa-robot"></i>&nbsp;<strong>SQL To Django ORM</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>
<main role="main">
    <section class="jumbotron text-center">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </section>
</main>


<footer class="text-muted">
    <div class="container">
        <p>2020 &copy; RIMI</p>
    </div>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
{% block footer-script %}
{% endblock %}
</body>
</html>

common/templates/widgets/attrs.html
{% for name, value in widget.attrs.items %}{% if value is not False %} {{ name }}{% if value is not True %}="{{ value|stringformat:'s' }}"{% endif %}{% endif %}{% endfor %}

common/templates/widgets/div_contenteditable.html
<div name="{{ widget.name }}" contenteditable="true" id="id_{{ widget.name }}" {% include "widgets/attrs.html" %}>
    {% if widget.value %}
    {{ widget.value }}
    {% endif %}
</div>

sql_to_django/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="mb-5">SQL To Django ORM</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.query }}
        <button type="submit" class="btn btn-primary btn-lg m-2"><i class="fas fa-sync-alt"></i></button>
    </form>
    <div class="card">
        <div class="card-header">
            Result
        </div>
        <div class="card-body">
            {{ orm }}
        </div>
    </div>
    <div class="text-left mt-5">
        <p>This Version Supported:SELECT, FROM, ORDER BY</p>
    </div>
{% endblock content %}

{% block footer-script %}
    <script>
    $(function () {
        {% if messages %}
            {% for message in messages %}
                alert('{{ message.tags }}: {{ message.message }}');
            {% endfor %}
        {% endif %}
    });
        // SQL keywords
        const keywords = ["SELECT", "FROM", "WHERE", "ORDER", "GROUP", "BY", "LIKE", "BETWEEN", "NOT", "FALSE", "NULL", "TRUE", "NOT IN", "DESC", "(CASE", "WHEN", "THEN"];
        // Keyup event
        $("#input_query").bind('input paste', function (e) {
            changeQuery(this, e);
        });
        $("#input_query").on("keyup", function (e) {
            changeQuery(this, e);
        });
        $("button[type=submit]").click(function () {
            $("#id_query").html($("#input_query").text());
        });

        function changeQuery(value, e) {
            // Space key pressed
            if (e.keyCode == 32 || e.keyCode == 13) {
                var newHTML = "";
                // Loop through words
                $(value).text().replace(/[\s]+/g, " ").trim().split(" ").forEach(function (val) {
                    // If word is statement
                    if (keywords.indexOf(val.trim().toUpperCase()) > -1)
                        newHTML += "<span class='statement'>" + val.toUpperCase() + "&nbsp;</span>";
                    else
                        newHTML += "<span class='other'>" + val + "&nbsp;</span>";
                });
                $(value).html(newHTML);
                // Set cursor postion to end of text
                var child = $(value).children();
                var range = document.createRange();
                var sel = window.getSelection();
                range.setStart(child[child.length - 1], 1);
                range.collapse(true);
                sel.removeAllRanges();
                sel.addRange(range);
                value.focus();
            }
        }
    </script>
{% endblock %}